baseURL = "https://omegagiven.github.io/omega-stories/"
languageCode = "en-us"
title = "Omega Stories"

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"

[pagination]
  pagerSize = 6

[params]
  description = "Short Stories by omegagiven and friends"
  author = "omegagiven"

[menu]
  [[menu.main]]
    name = "Stories"
    url = "/stories/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
